### ISSUE TITLE
building and setting up artoolkit5 for linux?

### ISSUE THREAD

**Issue by ralphtheninja** [artoolkit/jsartoolkit5#10]
So if I understand it correctly, in order to build this project you need to do (assuming pwd is the root of this project):

1. `git submodule update --init` to make sure `artoolkit5` is cloned and checked out
2.  run `./emscripten/artoolkit5/Configure`

So now the `Configure` will be asking me some questions. What should I pick as default settings in order to build this project successfully?

I don't really care about `clang` or `gcc`, I'm more concerned about which type of capture module I should pick e.g. `Video4Linux2` or `Video4Linux` or `IEEE 1394 Digital Video Camera` or `GStreamer` (I assume _one_ of them should be picked, or can I pick multiple?)

What about opencv, VRML and OpenSceneGraph?

**Comment by ThorstenBux** [comment]
Hi,
you do not need to bother with the building of the ARToolKit SDK. Emscripten builds all the things needed for you.

Do step one as you wrote.
Then do node `tools/makem.js` from the jsartoolkit directory (Ensure that you have installed Emscripten and python) 
Python: sudo apt-get install python
Emscripten: 
https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html

You can have a look at here https://github.com/artoolkit/jsartoolkit5/blob/master/README.md for build instructions.

Let me know if that works for you.

**Comment by ralphtheninja** [comment]
`node tools/makem.js` doesn't work, which is why I asked :)

![screenshot from 2016-03-11 11 30 45](https://cloud.githubusercontent.com/assets/308049/13699749/b89f5386-e77c-11e5-9761-8dee2e24ed4e.png)

I assume this is because I haven't `./Configure`'ed properly. Or am I missing something completely here?

**Comment by ThorstenBux** [comment]
Hi,

I was able to reproduce your error. There is one step missing in the build instructions. 

The only thing you need to do is to rename the config.h.in file located in `jsartoolkit/emscripten/artoolkit5/include/AR` in config.h

then your build should work.

Tell me if it does

**Comment by ralphtheninja** [comment]
> Hi,
> 
> I was able to reproduce your error. There is one step missing in the build instructions. (I fix that in enter a pull request)
> 
> The only thing you need to do is to rename the config.h.in file located in jsartoolkit/emscripten/artoolkit5/include/AR in config.h
> 
> then your build should work.
> 
> Tell me if it does

Awesome! I'll get right on testing that first thing tomorrow!

**Comment by cloud4every1** [comment]
Hi,
Tried to compile it today with the current artoolkit (downloaded it) but the compile fails on ubuntu.


_/jsartoolkit5/emscripten/ARToolKitJS.cpp:616:10: error: no matching function for call to 'arDetectMarker'
                return arDetectMarker( arc->arhandle, arc->videoFrame );
                       ^~~~~~~~~~~~~~
/jsartoolkit5/emscripten/artoolkit5/include/AR/ar.h:1045:16: note: candidate function not viable: no known conversion from 'ARUint8 *' (aka 'unsigned char *') to 'AR2VideoBufferT *' for 2nd argument
int            arDetectMarker(ARHandle *arHandle, AR2VideoBufferT *frame);
               ^
1 error generated.
ERROR    root: compiler frontend failed to generate LLVM bitcode, halting_

Thanks for your help
