### ISSUE TITLE
Create API reference

### ISSUE THREAD

**Issue by jensarps** [artoolkit/jsartoolkit5#19]
If you want to do anything more in-depth than a basic setup, it would be great if there was an API reference for `ARController` (and maybe also for `ARCameraParam`).

The steps to do this would be:
* Modify JSDoc blocks so they are being picked up by JSDoc
* Let JSDoc generate the API reference
* Merge the result into the `gh-pages` branch to be available online

Whenever improvements are being made to inline docs, the api reference could be updated.

In an ideal world, generating the docs would be done by a task runner like Grunt :)

If there is serious interest in this, I'd be up to do this.

**Comment by ralphtheninja** [comment]
Go nuts! We need a `package.json` soonish anyway I think so get some `grunt` going :)

**Comment by jensarps** [comment]
Sweet. That, however, will put #15 into the spotlight :)

**Comment by jensarps** [comment]
Closing this as #21 is merged.
