### ISSUE TITLE
How to add an effect on Three.js renderer ?

### ISSUE THREAD

**Issue by enguerranws** [artoolkit/jsartoolkit5#33]
Hi, 

I was using Three.js with StereoEffect (http://threejs.org/examples/webgl_effects_stereo.html). JSARToolkit5 seems to provide some good stuff, but right now, I can't figure how I can add an effect on the whole scene.

This is what I was doing (without JSARToolkit) : 

```
    var effect = new THREE.StereoEffect(renderer);
    effect.separation = 0;
    effect.setSize(window.innerWidth, window.innerHeight);
    [...]
    function render() {
      movieMaterial.update();
      backgroundTexture.update();
      effect.render(scene, camera);
    }
```

How can I simply apply this effect on my scene?

**Comment by jeromeetienne** [comment]
The way you render your three.js seems more a three.js question. It is independant to jsartoolkit per say. three.js questions are asked on stackoverflow, http://stackoverflow.com/search?q=three.js

You will get a better there

Good luck tho :)
