### ISSUE TITLE
artoolkit.getDetectedMarkers() is not a function

### ISSUE THREAD

**Issue by enguerranws** [artoolkit/jsartoolkit5#35]
Hi,

as said in the docs, I really would use artoolkit.getDetectedMarkers() to retrieve an array of the markers detected in the last process.

However, I get this error : artoolkit.getDetectedMarkers() is not a function. Exploring artoolkit object, I can see it doesn't exist.

So, my question is: how can I get an updated list of detected markers?

**Comment by enguerranws** [comment]
No ideas ?

**Comment by ThorstenBux** [comment]
@Neuroforge : Can you have a look?

**Comment by ascourtas** [comment]
So I had trouble with missing methods because I wasn't including the javascript files in the right order. Are you including them in the same order as in the examples?

**Comment by jeromeetienne** [comment]
Here is a way to do it

```javascript
var markerNum = this.getMarkerNum();
for (var i=0; i<markerNum; i++) {
    var markerInfo = this.getMarker(i);
    // ... here markerInfo is the info for the i-th marker
}
```

This can be found in ```ARController.prototype.process``` in artoolkit.api.js

https://github.com/artoolkit/jsartoolkit5/blob/master/js/artoolkit.api.js#L119


i hope this help
