### ISSUE TITLE
Using rear cam on Android - Chrome?

### ISSUE THREAD

**Issue by enguerranws** [artoolkit/jsartoolkit5#37]
Hi,

I'm using JSartoolkit in my mobile browser (Chrome on Android 7.0) and I'm trying to get the rear cam stream. However, I used many camera_para.dat, but I'm still getting the facing cam stream...

Can someone tell me how to get rear cam stream on mobile browsers?

**Comment by Neuroforge** [comment]
Please see this StackOverflow post regarding changing the android camera programmatically.

http://stackoverflow.com/questions/18483160/which-camera-will-open-getusermedia-api-in-mobile-device-front-or-rear

**Comment by enguerranws** [comment]
Hi @Neuroforge,

I did that several times using `navigator.getUserMedia`. But in this example, using JSArtoolkit:

`
window.ARThreeOnLoad = function() {

	ARController.getUserMediaThreeScene({
		maxARVideoSize: 640,
		cameraParam: 'Data/camera_para_android.dat',
		onSuccess: function(arScene, arController, arCamera) {
                    ...
                }
         });
}
`

I don't see how I can implement it as I can't find any documentation on `ARController.getUserMediaThreeScene();`.

Can I try something like that?

`
ARController.getUserMediaThreeScene({
		maxARVideoSize: 640,
		facingMode: { exact: 'environment'},
		onSuccess: function(arScene, arController, arCamera) {
                    ...
`

**Comment by jailson** [comment]
I am facing the same issue.

**Comment by enguerranws** [comment]
According to https://github.com/artoolkit/jsartoolkit5/blob/master/doc/introduction.html, I changed  the code above to use the `facing` property, with no success (I tried and tested it with `{ exact: 'environment'}` and just `'environment'`):

`
ARController.getUserMediaThreeScene({ 
      maxARVideoSize: 640, 
      facing: { exact: 'environment'},
      onSuccess: function(arScene, arController, arCamera) { ...
`

**Comment by enguerranws** [comment]
I go further tracking that bug. It seems that is a bug that comes from Chrome on Android, not related to JSartoolkit.

I've ended up modifying artoolkit.api.js, so that I use camera's id, not selecting a `facingMode`.

Right now, this is ugly: 

`
MediaStreamTrack.getSources(function(sources) {
				var newConstraints;
				var facingDir = mediaDevicesConstraints.facingMode;
				if (facing && facing.exact) {
					facingDir = facing.exact;
				}
				for (var i=0; i<sources.length; i++) {

					if (sources[i].kind === 'video' && sources[i].facing === facingDir) {
						newConstraints = {
							audio: false,
							video: {
								optional: [{sourceId: sources[i].id}]
							}
						}
						break;
					}
				}
				navigator.getUserMedia(newConstraints, success, onError);
`
