### ISSUE TITLE
ARController.getUserMedia - "DevicesNotFoundError"

### ISSUE THREAD

**Issue by DavideCapitola** [artoolkit/jsartoolkit5#43]
Hi all,
yesterday I was working on a project and everything worked fine. Today I started again, running the project on `Chrome version 55.0.2883.95` and I found this error inside `artoolkit.min.js`:

![screen shot 2017-01-13 at 15 16 44](https://cloud.githubusercontent.com/assets/17545356/21932944/63f4e57a-d9a3-11e6-816e-3acb9fe3799b.png)

Apparently this happens also in the [examples](https://artoolkit.github.io/jsartoolkit5/examples/) section.  Do you know what is the reason behind this issue?

Thanks in advance for your replies!

**Comment by Neuroforge** [comment]
This can occur if you have more than one browser window open that is using the device.

The devices are available to only one browser window at a time.

**Comment by DavideCapitola** [comment]
I don't think that was the issue, but now it works again on Chrome 55.0.2883.95

Thanks anyway!
