### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by issacnitin** [artoolkit/jsartoolkit5#77]
I see this is licensed LGPLv3, but shown in github as GPL3.

If I make an augmented reality development platform(like ZapWorks), and don't release the source code, is that a license violation?

**Comment by philip-lamb** [comment]
It’s LGPv3; GutHub’s license auto-detect isn’t always perfect. I got them to correct it on the native ARToolKit repo.

You don’t have to release source of your app, only any modifications you make to JSARToolKit.
