### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by DarrenGuinness** [artoolkit/jsartoolkit5#82]
Hi there, I have followed the build instructions found on the README, installed enscripten and activated the environment variables but seem to have encounter an error during the last step (npm run build). emconfigure doesn't seem to be a supported command. Is there a workaround for this?

output:
> npm run build

> jsartoolkit@0.0.0 build C:\Users\user1\Desktop\jsartoolkit5
> cd emscripten/artoolkit5/ && emconfigure ./configure && cd ../../ && node tools/makem.js; echo Built at `date`

'emconfigure' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jsartoolkit@0.0.0 build: `cd emscripten/artoolkit5/ && emconfigure ./configure && cd ../../ && node tools/makem.js; echo Built at `date``
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jsartoolkit@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:

**Comment by ThorstenBux** [comment]
@DarrenGuinness look here https://github.com/artoolkitx/jsartoolkit5/issues/63

**Comment by DarrenGuinness** [comment]
Hmm, must be an issue with emscripten. However the examples seem to execute properly when compared to the hosted examples ( https://artoolkit.github.io/jsartoolkit5/examples/ ).

**Comment by ThorstenBux** [comment]
@DarrenGuinness look here artoolkitx#63 as the project is continues as artoolkitX
