### ISSUE TITLE
Matrix Code Types

### ISSUE THREAD

**Issue by vitorpmoreira** [artoolkit/jsartoolkit5#90]
Hello,

If I'm not mistaken, it should be possible to use 5x5 matrix 2d barcodes, but after inspecting the available constants, there are only 3x3 and 4x4 as the available types (with the ecc versions as well). I checked the AR.h from the ARToolKit source code and got the const values for the 5x5 types, but when I set the matrix code type to a value, for example, 5x5 with haming 5, the IDs given from the "getMarker" event of the ARController are the same as the 5x5 WITHOUT error correction, which is wrong (with haming 5 there are around 4K markers, and without error correction there are more than 4 million)!

My question is, is the jsartoolkit5 limited, is this a bug or do I need to change something to make this work?

**Comment by philip-lamb** [comment]
Support for BCH codes on the 5x5 patterns was only added in July 2017 (in commit 77e9a5a71337674357876dc270cb86d45dd41b1d), so it's probable that this just hasn't been extended to JSARToolKit yet.

**Comment by vitorpmoreira** [comment]
Oh ok, thanks @philip-lamb ! So, giving the state of things, an update to JSARToolKit is probably not to be expected, right?

**Comment by ThorstenBux** [comment]
Here I've taken latest master from artoolkitx/artoolkit5 and rebuilt jsartoolkit API.

https://github.com/ThorstenBux/jsartoolkit5/tree/rebuild-latest-head-artkx/artk5

**Comment by vitorpmoreira** [comment]
@ThorstenBux  Thank you! Actually, after I saw the @philip-lamb answer, I went to the artoolkitx repo and downloaded the latest build of JSARToolkit5 and it worked like a charm!
Are there any crucial differences between your build and the one of ARToolKitX repository? Or are the same based on the latest ARToolKitX master?

**Comment by ThorstenBux** [comment]
artoolkitx/artoolkit5 might be slightly older then my build. but if it works for you, all good.
